name: Evaluate

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Générer les résultats d'évaluation (JSON)
        run: python generate_evaluation_results.py

      - name: Run evaluation
        run: python evaluate.py

      - name: Générer le rapport de performance
        run: python generate_report.py

      - name: Vérifier les performances
        run: |
          ACCURACY=$(awk -F',' 'NR==2 {print $2}' performance_report.csv)
          if (( $(echo "$ACCURACY < 0.75" | bc -l) )); then
            echo "⚠️ Attention, la précision est en baisse : $ACCURACY" | tee performance_alert.txt
          fi
